language: cpp

install:
  - pip install --user conan cmake
git:
  depth: 3
jobs:
  include:
    - os: linux
      dist: focal
      compiler: gcc
      env:
        - MATRIX_EVAL="CC=gcc-10 && CXX=g++-10"

      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-10
            - g++-10

      after_script:
        - bash <(curl -s https://codecov.io/bash) -x /usr/bin/gcov-${GCC_VER}
    - os: linux
      dist: focal
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-focal-10.0
          packages:
            # for the udpated libstdc++
            - gcc-10
            - g++-10
            - clang-10
      env:
        - MATRIX_EVAL="CC=clang-10 && CXX=clang++-10"

before_script:
  - eval "${MATRIX_EVAL}"

script:
  - mkdir build
  - cd build
  - conan install ..
  - cmake ../
  - cmake --build . -- -j2
  - ctest -j2
